In [7]:
#Array Creation
#1.Create a 1D array of numbers from 10 to 50.
import numpy as np
arr=np.array(list(range(10,51)))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [79]:
#Create a 3x3 array of random numbers between 0 and 1.
arr2 = np.random.random((3, 3))
arr2

array([[0.30393155, 0.76315164, 0.14092945],
       [0.02418347, 0.8280373 , 0.36394161],
       [0.48989317, 0.28218975, 0.91161508]])

In [17]:
#2.Array Attributes
print(arr.shape)
print(arr2.size)
print(arr2.dtype)

(41,)
9
float64


In [20]:
#3.	Basic Operations
#o	Add 5 to every element of a 1D array.
a=np.array([1,2,3,4,5])
a=a+5
a


array([ 6,  7,  8,  9, 10])

In [21]:
#Matrix Multiplication
c=np.array([[1,2],[4,5]])
d=np.array([[2,3],[5,6]])
np.dot(c,d)

array([[12, 15],
       [33, 42]])

In [41]:
#4.	Indexing and Slicing
arr4=np.arange(1,26).reshape(5,5)
print("The first row:",arr4[:1])
print("The last column:",arr4[:,-1])
print("A subarray of the first three rows and first two columns:",arr4[:3,:2])

The first row: [[1 2 3 4 5]]
The last column: [ 5 10 15 20 25]
A subarray of the first three rows and first two columns: [[ 1  2]
 [ 6  7]
 [11 12]]


In [44]:
#5.	Aggregation
#o	Create a 10-element array of random integers between 1 and 100. Find:
arr5=np.random.randint(1, 101, 10)
print(arr5)
print("The maximum value:",arr5.max())
print("The manimum value:",arr5.min())
print("The mean is:",arr5.mean())
print("The Standard deviation:",arr5.std())

[ 6  8 65 67 36 11 92 72 73 58]
The maximum value: 92
The manimum value: 6
The mean is: 48.8
The Standard deviation: 29.593242471888743


In [45]:
#6.	Reshaping
#o	Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
arr6=np.arange(1,13).reshape(3,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
#7.	Broadcasting
#o	Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
arr7=np.ones((3,3))
arr7+=[1,2,3]
arr7

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [72]:
#8.	Filtering
#o	Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
arr8 = np.arange(1, 51) 


filtered_arr = arr8[arr8 % 5 == 0]
filtered_arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [75]:
#9.	Matrix Multiplication
#o	Create two 2x2 matrices and perform matrix multiplication.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
result

array([[19, 22],
       [43, 50]])

In [77]:
#10.	Advanced Indexing
#o	Given a 4x4 array, use fancy indexing to extract the diagonal elements.
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# Fancy indexing to extract diagonal elements
diagonal = arr[np.arange(4), np.arange(4)]


print("Diagonal elements:", diagonal)

Diagonal elements: [ 1  6 11 16]
